version: '3'

services:
  cozy-dingtalk-sync:
    image: 192.168.1.252:15000/cozy-dingtalk-sync:latest
    container_name: cozy-dingtalk-sync
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./output:/app/output
      - ./sync-time:/app/sync-time
